### ISSUE TITLE
Strider Rock to Broken Strider Egg Recipe (Cutting Board) Broken?

### ISSUE THREAD

**Issue by PurgeWicks** [rotgruengelb/MyNethersDelightRefabricated#3]
![image](https://github.com/user-attachments/assets/1343648f-6a25-41a8-befc-e5aa79e0a6b7)

The cutting board recipe turning a strider rock to a broken strider egg seems to not have anything to transform the rock. Used every tool there is. I have tried only using My Nether's Delight in the instance, problem still persists. Not sure if this is also happening on Forge, though I doubt it.

Loving the (Fabric) port of the mod regardless!!!

**Comment by BlueIsADude** [comment]
Ran into this too, and looking at the data folder in the source code, it seems that the recipe is using the wrong tag for pickaxes, using c:tools/pickaxes instead of minecraft:pickaxes. This is an issue for quite a few recipes even! All of the broken tags seem to be mainly related to raw meat, milk, and individual veggies.

This is easily fixable with a datapack for now.

**Comment by ChrysanthCow** [comment]
I'll get to fixing these in a bit. Differences in tags moment.
